package cabalaccessorys.client;

import cabalaccessorys.RegisterItem;
import cabalaccessorys.ServerSide;
import cabalaccessorys.faction;
import cabalaccessorys.guinewscreen;
import cabalaccessorys.keyexgui;
import cabalaccessorys.rendergachapon;
import cabalaccessorys.rendergachapon2;
import cabalaccessorys.tegacha;
import cabalaccessorys.tegacha2;
import cabalaccessorys.blockshop.sellerentity;
import cabalaccessorys.blockshop.sellermodel;
import cabalaccessorys.blockshop.sellerrender;
import cabalaccessorys.blockshop.npc.npcentity;
import cabalaccessorys.blockshop.npc.npcmodel;
import cabalaccessorys.blockshop.npc.npcrender;
import cabalaccessorys.bossavatar.Avatar01model;
import cabalaccessorys.client.rendersword.RenderSword1;
import cabalaccessorys.client.rendersword.RenderSword10;
import cabalaccessorys.client.rendersword.RenderSword11;
import cabalaccessorys.client.rendersword.RenderSword12;
import cabalaccessorys.client.rendersword.RenderSword13;
import cabalaccessorys.client.rendersword.RenderSword14;
import cabalaccessorys.client.rendersword.RenderSword15;
import cabalaccessorys.client.rendersword.RenderSword16;
import cabalaccessorys.client.rendersword.RenderSword17;
import cabalaccessorys.client.rendersword.RenderSword18;
import cabalaccessorys.client.rendersword.RenderSword19;
import cabalaccessorys.client.rendersword.RenderSword2;
import cabalaccessorys.client.rendersword.RenderSword20;
import cabalaccessorys.client.rendersword.RenderSword21;
import cabalaccessorys.client.rendersword.RenderSword3;
import cabalaccessorys.client.rendersword.RenderSword4;
import cabalaccessorys.client.rendersword.RenderSword5;
import cabalaccessorys.client.rendersword.RenderSword6;
import cabalaccessorys.client.rendersword.RenderSword7;
import cabalaccessorys.client.rendersword.RenderSword8;
import cabalaccessorys.client.rendersword.RenderSword9;
import cabalaccessorys.client.renderswordcabal2d.RenderWeaponA;
import cabalaccessorys.client.renderswordcabal3d.RenderSword01;
import cabalaccessorys.entity.mon01entity;
import cabalaccessorys.entity.mon01model;
import cabalaccessorys.entity.mon01render;
import cabalaccessorys.entity.mon02entity;
import cabalaccessorys.entity.mon02model;
import cabalaccessorys.entity.mon02render;
import cabalaccessorys.entity.mon03entity;
import cabalaccessorys.entity.mon03model;
import cabalaccessorys.entity.mon03render;
import cabalaccessorys.entity.mon04entity;
import cabalaccessorys.entity.mon04model;
import cabalaccessorys.entity.mon04render;
import cabalaccessorys.entity.mon05entity;
import cabalaccessorys.entity.mon05model;
import cabalaccessorys.entity.mon05render;
import cabalaccessorys.entity.mon06entity;
import cabalaccessorys.entity.mon06model;
import cabalaccessorys.entity.mon06render;
import cabalaccessorys.entity.mon07entity;
import cabalaccessorys.entity.mon07model;
import cabalaccessorys.entity.mon07render;
import cabalaccessorys.entity.mon08entity;
import cabalaccessorys.entity.mon08model;
import cabalaccessorys.entity.mon08render;
import cabalaccessorys.entity.monentity09;
import cabalaccessorys.entity.monentity10;
import cabalaccessorys.entity.monentity11;
import cabalaccessorys.entity.monentity12;
import cabalaccessorys.entity.monentity13;
import cabalaccessorys.entity.monentity14;
import cabalaccessorys.entity.monentity15;
import cabalaccessorys.entity.monentity16;
import cabalaccessorys.entity.monentity17;
import cabalaccessorys.entity.monentity18;
import cabalaccessorys.entity.monentity19;
import cabalaccessorys.entity.monentity20;
import cabalaccessorys.entity.monmodel09;
import cabalaccessorys.entity.monmodel10;
import cabalaccessorys.entity.monmodel11;
import cabalaccessorys.entity.monmodel12;
import cabalaccessorys.entity.monmodel13;
import cabalaccessorys.entity.monmodel14;
import cabalaccessorys.entity.monmodel15;
import cabalaccessorys.entity.monmodel16;
import cabalaccessorys.entity.monmodel17;
import cabalaccessorys.entity.monmodel18;
import cabalaccessorys.entity.monmodel19;
import cabalaccessorys.entity.monmodel20;
import cabalaccessorys.entity.monrender09;
import cabalaccessorys.entity.monrender10;
import cabalaccessorys.entity.monrender11;
import cabalaccessorys.entity.monrender12;
import cabalaccessorys.entity.monrender13;
import cabalaccessorys.entity.monrender14;
import cabalaccessorys.entity.monrender15;
import cabalaccessorys.entity.monrender16;
import cabalaccessorys.entity.monrender17;
import cabalaccessorys.entity.monrender18;
import cabalaccessorys.entity.monrender19;
import cabalaccessorys.entity.monrender20;
import cabalaccessorys.entity.headplayer.EntityHeadPlayer;
import cabalaccessorys.entity.headplayer.EntityHeadPlayerModel;
import cabalaccessorys.entity.headplayer.EntityHeadPlayerRender;
import cabalaccessorys.guishop.ModelShop;
import cabalaccessorys.guishop.npc.ModelShopNPC;
import cabalaccessorys.guiskill.KeyPotion;
import cabalaccessorys.guiskill.KeySetSkill;
import cabalaccessorys.guiskill.KeySkill1;
import cabalaccessorys.guiskill.KeySkill2;
import cabalaccessorys.guiskill.KeySkill3;
import cabalaccessorys.guiskill.KeySkill4;
import cabalaccessorys.guiskill.KeySkill5;
import cabalaccessorys.guiskill.SkillGui;
import cabalaccessorys.guiwinwar.WinwarGui;
import cabalaccessorys.pet.pet01entity;
import cabalaccessorys.pet.pet01model;
import cabalaccessorys.pet.pet02entity;
import cabalaccessorys.pet.pet02model;
import cabalaccessorys.soundevent.EventHandlerSound;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.network.simpleimpl.MessageContext;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.client.MinecraftForgeClient;
import net.minecraftforge.common.MinecraftForge;
import sp.EntityCustomMobBase;
import sp.EntityCustomMobRender;
import sp.ModelEntityCustomMob;
import sp.RenderBlockSpawn;
import sp.SpawnBlockTileEntity;

public class GuestSide extends ServerSide {
   private static Minecraft mc = Minecraft.func_71410_x();
   @SideOnly(Side.CLIENT)
   public static final ModelBase shop = new ModelShop();
   @SideOnly(Side.CLIENT)
   public static final ModelBase shopnpc1 = new ModelShopNPC();
   @SideOnly(Side.CLIENT)
   public static final ModelBase faction = new faction();
   @SideOnly(Side.CLIENT)
   public static final ModelBiped avatar1 = new Avatar01model();

   public EntityPlayer getPlayerEntity(MessageContext ctx) {
      return (EntityPlayer)(ctx.side.isClient() ? Minecraft.func_71410_x().field_71439_g : super.getPlayerEntity(ctx));
   }

   public void reg() {
      FMLCommonHandler.instance().bus().register(new KeySkill1());
      FMLCommonHandler.instance().bus().register(new KeySkill2());
      FMLCommonHandler.instance().bus().register(new KeySkill3());
      FMLCommonHandler.instance().bus().register(new KeySkill4());
      FMLCommonHandler.instance().bus().register(new KeySkill5());
      FMLCommonHandler.instance().bus().register(new KeyPotion());
      FMLCommonHandler.instance().bus().register(new keyexgui());
      FMLCommonHandler.instance().bus().register(new KeySetSkill());
      FMLCommonHandler.instance().bus().register(new KeyOpenHat());
      MinecraftForge.EVENT_BUS.register(new guinewscreen(mc));
      MinecraftForge.EVENT_BUS.register(new EventHandlerItemTooltip());
      MinecraftForge.EVENT_BUS.register(new EventHandlerSound());
      ClientRegistry.bindTileEntitySpecialRenderer(tegacha.class, new rendergachapon());
      ClientRegistry.bindTileEntitySpecialRenderer(tegacha2.class, new rendergachapon2());
      ClientRegistry.bindTileEntitySpecialRenderer(SpawnBlockTileEntity.class, new RenderBlockSpawn());
      MinecraftForge.EVENT_BUS.register(new SkillGui(mc));
      MinecraftForge.EVENT_BUS.register(new WinwarGui(mc));
      RenderingRegistry.registerEntityRenderingHandler(mon01entity.class, new mon01render(new mon01model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon02entity.class, new mon02render(new mon02model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon03entity.class, new mon03render(new mon03model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon04entity.class, new mon04render(new mon04model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon05entity.class, new mon05render(new mon05model(1.0F), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon06entity.class, new mon06render(new mon06model(1.0F), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon07entity.class, new mon07render(new mon07model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(mon08entity.class, new mon08render(new mon08model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity09.class, new monrender09(new monmodel09(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity10.class, new monrender10(new monmodel10(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity11.class, new monrender11(new monmodel11(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity12.class, new monrender12(new monmodel12(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity13.class, new monrender13(new monmodel13(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity14.class, new monrender14(new monmodel14(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity15.class, new monrender15(new monmodel15(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity16.class, new monrender16(new monmodel16(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity17.class, new monrender17(new monmodel17(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity18.class, new monrender18(new monmodel18(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity19.class, new monrender19(new monmodel19(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(monentity20.class, new monrender20(new monmodel20(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(pet01entity.class, new mon01render(new pet01model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(pet02entity.class, new mon07render(new pet02model(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(sellerentity.class, new sellerrender(new sellermodel(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(npcentity.class, new npcrender(new npcmodel(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(EntityCustomMobBase.class, new EntityCustomMobRender(new ModelEntityCustomMob(), 1.0F));
      RenderingRegistry.registerEntityRenderingHandler(EntityHeadPlayer.class, new EntityHeadPlayerRender(new EntityHeadPlayerModel(), 1.0F));
   }

   public void renderweapon() {
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw01a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw02a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw03a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw04a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw05a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw06a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw07a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw08a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw09a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw10a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw11a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw12a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw13a, new RenderWeaponA());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw001, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw002, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw003, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw004, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw005, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw006, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw007, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw008, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw009, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.sw010, new RenderSword01());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon1, new RenderSword1());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon2, new RenderSword2());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon3, new RenderSword3());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon4, new RenderSword4());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon5, new RenderSword5());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon6, new RenderSword6());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon7, new RenderSword7());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon8, new RenderSword8());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon9, new RenderSword9());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon10, new RenderSword10());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon11, new RenderSword11());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon12, new RenderSword12());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon13, new RenderSword13());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon14, new RenderSword14());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon15, new RenderSword15());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon16, new RenderSword16());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon17, new RenderSword17());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon18, new RenderSword18());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon19, new RenderSword19());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon20, new RenderSword20());
      MinecraftForgeClient.registerItemRenderer(RegisterItem.newweapon21, new RenderSword21());
   }
}
