package api.player.model;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;

public final class ModelPlayerClassVisitor extends ClassVisitor {
   public static final String targetClassName = "api.player.model.ModelPlayer";
   public static final String obfuscatedClassReference = "api/player/model/ModelPlayer";
   public static final String obfuscatedSuperClassReference = "bhm";
   public static final String deobfuscatedClassReference = "api/player/model/ModelPlayer";
   public static final String deobfuscateSuperClassReference = "net/minecraft/client/model/ModelBiped";
   private boolean hadLocalGetRandomModelBox;
   private boolean hadLocalGetTextureOffset;
   private boolean hadLocalRender;
   private boolean hadLocalRenderCloak;
   private boolean hadLocalRenderEars;
   private boolean hadLocalSetLivingAnimations;
   private boolean hadLocalSetRotationAngles;
   private boolean hadLocalSetTextureOffset;
   private final boolean isObfuscated;

   public static byte[] transform(byte[] bytes, boolean isObfuscated) {
      try {
         ByteArrayInputStream in = new ByteArrayInputStream(bytes);
         ClassReader cr = new ClassReader(in);
         ClassWriter cw = new ClassWriter(1);
         ModelPlayerClassVisitor p = new ModelPlayerClassVisitor(cw, isObfuscated);
         cr.accept(p, 0);
         byte[] result = cw.toByteArray();
         in.close();
         return result;
      } catch (IOException var7) {
         throw new RuntimeException(var7);
      }
   }

   public ModelPlayerClassVisitor(ClassVisitor classVisitor, boolean isObfuscated) {
      super(262144, classVisitor);
      this.isObfuscated = isObfuscated;
   }

   public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
      if (this.isObfuscated && superName.equals("net/minecraft/client/model/ModelBiped")) {
         superName = "bhm";
      }

      String[] newInterfaces = new String[interfaces.length + 1];

      for(int i = 0; i < interfaces.length; ++i) {
         newInterfaces[i] = interfaces[i];
      }

      newInterfaces[interfaces.length] = "api/player/model/IModelPlayerAPI";
      super.visit(version, access, name, signature, superName, newInterfaces);
   }

   public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
      if (name.equals("<init>")) {
         desc = "(FLjava/lang/String;)V";
         MethodVisitor mv = this.cv.visitMethod(1, "<init>", "(F)V", signature, exceptions);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(23, 1);
         mv.visitInsn(1);
         mv.visitMethodInsn(183, "api/player/model/ModelPlayer", "<init>", desc);
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
         return new ModelPlayerConstructorVisitor(super.visitMethod(access, name, desc, signature, exceptions), this.isObfuscated);
      } else if (name.equals(this.isObfuscated ? "a" : "getRandomModelBox") && desc.equals(this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;")) {
         this.hadLocalGetRandomModelBox = true;
         return super.visitMethod(17, "localGetRandomModelBox", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "a" : "getTextureOffset") && desc.equals(this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;")) {
         this.hadLocalGetTextureOffset = true;
         return super.visitMethod(17, "localGetTextureOffset", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "a" : "render") && desc.equals(this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V")) {
         this.hadLocalRender = true;
         return super.visitMethod(17, "localRender", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "c" : "renderCloak") && desc.equals("(F)V")) {
         this.hadLocalRenderCloak = true;
         return super.visitMethod(17, "localRenderCloak", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "b" : "renderEars") && desc.equals("(F)V")) {
         this.hadLocalRenderEars = true;
         return super.visitMethod(17, "localRenderEars", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "a" : "setLivingAnimations") && desc.equals(this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V")) {
         this.hadLocalSetLivingAnimations = true;
         return super.visitMethod(17, "localSetLivingAnimations", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "a" : "setRotationAngles") && desc.equals(this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V")) {
         this.hadLocalSetRotationAngles = true;
         return super.visitMethod(17, "localSetRotationAngles", desc, signature, exceptions);
      } else if (name.equals(this.isObfuscated ? "a" : "setTextureOffset") && desc.equals("(Ljava/lang/String;II)V")) {
         this.hadLocalSetTextureOffset = true;
         return super.visitMethod(17, "localSetTextureOffset", desc, signature, exceptions);
      } else {
         return super.visitMethod(access, name, desc, signature, exceptions);
      }
   }

   public void visitEnd() {
      MethodVisitor mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "getRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getRandomModelBox", "(Lapi/player/model/IModelPlayerAPI;Ljava/util/Random;)" + (this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realGetRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "getRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superGetRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "getRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalGetRandomModelBox) {
         mv = this.cv.visitMethod(17, "localGetRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(25, 1);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "getRandomModelBox", "" + (this.isObfuscated ? "(Ljava/util/Random;)Lbix;" : "(Ljava/util/Random;)Lnet/minecraft/client/model/ModelRenderer;") + "");
         mv.visitInsn(176);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "getTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getTextureOffset", "(Lapi/player/model/IModelPlayerAPI;Ljava/lang/String;)" + (this.isObfuscated ? "Lbiy;" : "Lnet/minecraft/client/model/TextureOffset;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realGetTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "getTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superGetTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "getTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalGetTextureOffset) {
         mv = this.cv.visitMethod(17, "localGetTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(25, 1);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "getTextureOffset", "" + (this.isObfuscated ? "(Ljava/lang/String;)Lbiy;" : "(Ljava/lang/String;)Lnet/minecraft/client/model/TextureOffset;") + "");
         mv.visitInsn(176);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "render", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(23, 7);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "render", "(Lapi/player/model/IModelPlayerAPI;" + (this.isObfuscated ? "Lsa;FFFFFF" : "Lnet/minecraft/entity/Entity;FFFFFF") + ")V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realRender", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(23, 7);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "render", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superRender", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(23, 7);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "render", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalRender) {
         mv = this.cv.visitMethod(17, "localRender", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(25, 1);
         mv.visitVarInsn(23, 2);
         mv.visitVarInsn(23, 3);
         mv.visitVarInsn(23, 4);
         mv.visitVarInsn(23, 5);
         mv.visitVarInsn(23, 6);
         mv.visitVarInsn(23, 7);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "render", "" + (this.isObfuscated ? "(Lsa;FFFFFF)V" : "(Lnet/minecraft/entity/Entity;FFFFFF)V") + "");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "c" : "renderCloak", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "renderCloak", "(Lapi/player/model/IModelPlayerAPI;F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realRenderCloak", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "c" : "renderCloak", "(F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superRenderCloak", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "c" : "renderCloak", "(F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalRenderCloak) {
         mv = this.cv.visitMethod(17, "localRenderCloak", "(F)V", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(23, 1);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "c" : "renderCloak", "(F)V");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "b" : "renderEars", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "renderEars", "(Lapi/player/model/IModelPlayerAPI;F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realRenderEars", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "b" : "renderEars", "(F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superRenderEars", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "b" : "renderEars", "(F)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalRenderEars) {
         mv = this.cv.visitMethod(17, "localRenderEars", "(F)V", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(23, 1);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "b" : "renderEars", "(F)V");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "setLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "setLivingAnimations", "(Lapi/player/model/IModelPlayerAPI;" + (this.isObfuscated ? "Lsv;FFF" : "Lnet/minecraft/entity/EntityLivingBase;FFF") + ")V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realSetLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "setLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superSetLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalSetLivingAnimations) {
         mv = this.cv.visitMethod(17, "localSetLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(25, 1);
         mv.visitVarInsn(23, 2);
         mv.visitVarInsn(23, 3);
         mv.visitVarInsn(23, 4);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setLivingAnimations", "" + (this.isObfuscated ? "(Lsv;FFF)V" : "(Lnet/minecraft/entity/EntityLivingBase;FFF)V") + "");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "setRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(25, 7);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "setRotationAngles", "(Lapi/player/model/IModelPlayerAPI;" + (this.isObfuscated ? "FFFFFFLsa;" : "FFFFFFLnet/minecraft/entity/Entity;") + ")V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realSetRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(25, 7);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "setRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superSetRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitVarInsn(23, 2);
      mv.visitVarInsn(23, 3);
      mv.visitVarInsn(23, 4);
      mv.visitVarInsn(23, 5);
      mv.visitVarInsn(23, 6);
      mv.visitVarInsn(25, 7);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalSetRotationAngles) {
         mv = this.cv.visitMethod(17, "localSetRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(23, 1);
         mv.visitVarInsn(23, 2);
         mv.visitVarInsn(23, 3);
         mv.visitVarInsn(23, 4);
         mv.visitVarInsn(23, 5);
         mv.visitVarInsn(23, 6);
         mv.visitVarInsn(25, 7);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setRotationAngles", "" + (this.isObfuscated ? "(FFFFFFLsa;)V" : "(FFFFFFLnet/minecraft/entity/Entity;)V") + "");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(1, this.isObfuscated ? "a" : "setTextureOffset", "(Ljava/lang/String;II)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(21, 2);
      mv.visitVarInsn(21, 3);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "setTextureOffset", "(Lapi/player/model/IModelPlayerAPI;Ljava/lang/String;II)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "realSetTextureOffset", "(Ljava/lang/String;II)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(21, 2);
      mv.visitVarInsn(21, 3);
      mv.visitMethodInsn(182, "api/player/model/ModelPlayer", this.isObfuscated ? "a" : "setTextureOffset", "(Ljava/lang/String;II)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "superSetTextureOffset", "(Ljava/lang/String;II)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(21, 2);
      mv.visitVarInsn(21, 3);
      mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setTextureOffset", "(Ljava/lang/String;II)V");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      if (!this.hadLocalSetTextureOffset) {
         mv = this.cv.visitMethod(17, "localSetTextureOffset", "(Ljava/lang/String;II)V", (String)null, (String[])null);
         mv.visitVarInsn(25, 0);
         mv.visitVarInsn(25, 1);
         mv.visitVarInsn(21, 2);
         mv.visitVarInsn(21, 3);
         mv.visitMethodInsn(183, this.isObfuscated ? "bhm" : "net/minecraft/client/model/ModelBiped", this.isObfuscated ? "a" : "setTextureOffset", "(Ljava/lang/String;II)V");
         mv.visitInsn(177);
         mv.visitMaxs(0, 0);
         mv.visitEnd();
      }

      mv = this.cv.visitMethod(17, "getAimedBowField", "()Z", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "o" : "aimedBow", "Z");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setAimedBowField", "(Z)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "o" : "aimedBow", "Z");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedBodyField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "e" : "bipedBody", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedBodyField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "e" : "bipedBody", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedCloakField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "k" : "bipedCloak", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedCloakField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "k" : "bipedCloak", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedEarsField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "j" : "bipedEars", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedEarsField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "j" : "bipedEars", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedHeadField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "c" : "bipedHead", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedHeadField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "c" : "bipedHead", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedHeadwearField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "d" : "bipedHeadwear", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedHeadwearField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "d" : "bipedHeadwear", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedLeftArmField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "g" : "bipedLeftArm", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedLeftArmField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "g" : "bipedLeftArm", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedLeftLegField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "i" : "bipedLeftLeg", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedLeftLegField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "i" : "bipedLeftLeg", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedRightArmField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "f" : "bipedRightArm", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedRightArmField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "f" : "bipedRightArm", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBipedRightLegField", this.isObfuscated ? "()Lbix;" : "()Lnet/minecraft/client/model/ModelRenderer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "h" : "bipedRightLeg", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBipedRightLegField", this.isObfuscated ? "(Lbix;)V" : "(Lnet/minecraft/client/model/ModelRenderer;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "h" : "bipedRightLeg", this.isObfuscated ? "Lbix;" : "Lnet/minecraft/client/model/ModelRenderer;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getBoxListField", "()Ljava/util/List;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "r" : "boxList", "Ljava/util/List;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setBoxListField", "(Ljava/util/List;)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "r" : "boxList", "Ljava/util/List;");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getHeldItemLeftField", "()I", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "l" : "heldItemLeft", "I");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setHeldItemLeftField", "(I)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "l" : "heldItemLeft", "I");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getHeldItemRightField", "()I", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "m" : "heldItemRight", "I");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setHeldItemRightField", "(I)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "m" : "heldItemRight", "I");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getIsChildField", "()Z", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "s" : "isChild", "Z");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setIsChildField", "(Z)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "s" : "isChild", "Z");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getIsRidingField", "()Z", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "q" : "isRiding", "Z");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setIsRidingField", "(Z)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "q" : "isRiding", "Z");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getIsSneakField", "()Z", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "n" : "isSneak", "Z");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setIsSneakField", "(Z)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "n" : "isSneak", "Z");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getOnGroundField", "()F", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "p" : "onGround", "F");
      mv.visitInsn(174);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setOnGroundField", "(F)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(23, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "p" : "onGround", "F");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getTextureHeightField", "()I", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "u" : "textureHeight", "I");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setTextureHeightField", "(I)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "u" : "textureHeight", "I");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getTextureWidthField", "()I", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", this.isObfuscated ? "t" : "textureWidth", "I");
      mv.visitInsn(172);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "setTextureWidthField", "(I)V", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(21, 1);
      mv.visitFieldInsn(181, "api/player/model/ModelPlayer", this.isObfuscated ? "t" : "textureWidth", "I");
      mv.visitInsn(177);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getModelPlayerBase", "(Ljava/lang/String;)Lapi/player/model/ModelPlayerBase;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getModelPlayerBase", "(Lapi/player/model/IModelPlayerAPI;Ljava/lang/String;)Lapi/player/model/ModelPlayerBase;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getModelPlayerBaseIds", "()Ljava/util/Set;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getModelPlayerBaseIds", "(Lapi/player/model/IModelPlayerAPI;)Ljava/util/Set;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getExpandParameter", "()F", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getExpandParameter", "(Lapi/player/model/IModelPlayerAPI;)F");
      mv.visitInsn(174);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getModelPlayerType", "()Ljava/lang/String;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getModelPlayerType", "(Lapi/player/model/IModelPlayerAPI;)Ljava/lang/String;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "dynamic", "(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitVarInsn(25, 1);
      mv.visitVarInsn(25, 2);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "dynamic", "(Lapi/player/model/IModelPlayerAPI;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getModelPlayerAPI", "()Lapi/player/model/ModelPlayerAPI;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitFieldInsn(180, "api/player/model/ModelPlayer", "modelPlayerAPI", "Lapi/player/model/ModelPlayerAPI;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(17, "getModelPlayer", "()Lapi/player/model/ModelPlayer;", (String)null, (String[])null);
      mv.visitVarInsn(25, 0);
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      mv = this.cv.visitMethod(9, "getAllInstances", "()[Lapi/player/model/ModelPlayer;", (String)null, (String[])null);
      mv.visitMethodInsn(184, "api/player/model/ModelPlayerAPI", "getAllInstances", "()[Lapi/player/model/ModelPlayer;");
      mv.visitInsn(176);
      mv.visitMaxs(0, 0);
      mv.visitEnd();
      this.cv.visitField(18, "modelPlayerAPI", "Lapi/player/model/ModelPlayerAPI;", (String)null, (Object)null);
   }
}
