package farmmode;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;

public class ReqFishItem {
   public static Item FishFood1;
   public static Item FishFood2;
   public static Item FishFood3;
   public static Item FishFood4;
   public static Item FishFood5;
   public static Item FishFood6;
   public static Item FishFood7;
   public static Item Fish00;
   public static Item Fish01;
   public static Item Fish02;
   public static Item Fish03;
   public static Item Fish04;
   public static Item Fish05;
   public static Item Fish06;
   public static Item Fish07;
   public static Item Fish08;
   public static Item Fish09;
   public static Item Fish10;
   public static Item Fish11;
   public static Item Fish12;
   public static Item Fish13;
   public static Item Fish14;
   public static Item Fish15;
   public static Item Fish16;
   public static Item Fish17;
   public static Item Fish18;
   public static Item Fish19;
   public static Item Fish20;
   public static Item Fish21;
   public static Item Fish22;
   public static Item Fish23;
   public static Item Fish24;
   public static Item Fish25;
   public static Item Fish26;
   public static Item Fish27;
   public static Item Fish28;
   public static Item Fish29;
   public static Item Fish30;
   public static Item Fish31;
   public static Item Fish32;
   public static Item Fish33;
   public static Item Fish34;
   public static Item Fish35;
   public static Item Fish36;
   public static Item Fish37;
   public static Item Fish38;
   public static Item Fish39;
   public static Item Fish40;
   public static Item Fish41;
   public static Item FishStick;
   public static Item FishBoot;
   public static Item FishBottle;
   public static Block SeaWeed1;
   public static Block SeaWeed2;
   public static Block SeaWeed3;
   public static Block SeaWeed4;
   public static Block SeaWeed5;

   public static void its() {
      FishFood1 = new ItemFoodFish("FishFood1");
      GameRegistry.registerItem(FishFood1, "FishFood1");
      FishFood2 = new ItemFoodFish("FishFood2");
      GameRegistry.registerItem(FishFood2, "FishFood2");
      FishFood3 = new ItemFoodFish("FishFood3");
      GameRegistry.registerItem(FishFood3, "FishFood3");
      FishFood4 = new ItemFoodFish("FishFood4");
      GameRegistry.registerItem(FishFood4, "FishFood4");
      FishFood5 = new ItemFoodFish("FishFood5");
      GameRegistry.registerItem(FishFood5, "FishFood5");
      FishFood6 = new ItemFoodFish("FishFood6");
      GameRegistry.registerItem(FishFood6, "FishFood6");
      FishFood7 = new ItemFoodFish("FishFood7");
      GameRegistry.registerItem(FishFood7, "FishFood7");
      Fish00 = new ItemFish("Fish00");
      GameRegistry.registerItem(Fish00, "Fish00");
      Fish01 = new ItemFish("Fish01");
      GameRegistry.registerItem(Fish01, "Fish01");
      Fish02 = new ItemFish("Fish02");
      GameRegistry.registerItem(Fish02, "Fish02");
      Fish03 = new ItemFish("Fish03");
      GameRegistry.registerItem(Fish03, "Fish03");
      Fish04 = new ItemFish("Fish04");
      GameRegistry.registerItem(Fish04, "Fish04");
      Fish05 = new ItemFish("Fish05");
      GameRegistry.registerItem(Fish05, "Fish05");
      Fish06 = new ItemFish("Fish06");
      GameRegistry.registerItem(Fish06, "Fish06");
      Fish07 = new ItemFish("Fish07");
      GameRegistry.registerItem(Fish07, "Fish07");
      Fish08 = new ItemFish("Fish08");
      GameRegistry.registerItem(Fish08, "Fish08");
      Fish09 = new ItemFish("Fish09");
      GameRegistry.registerItem(Fish09, "Fish09");
      Fish10 = new ItemFish("Fish10");
      GameRegistry.registerItem(Fish10, "Fish10");
      Fish11 = new ItemFish("Fish11");
      GameRegistry.registerItem(Fish11, "Fish11");
      Fish12 = new ItemFish("Fish12");
      GameRegistry.registerItem(Fish12, "Fish12");
      Fish13 = new ItemFish("Fish13");
      GameRegistry.registerItem(Fish13, "Fish13");
      Fish14 = new ItemFish("Fish14");
      GameRegistry.registerItem(Fish14, "Fish14");
      Fish15 = new ItemFish("Fish15");
      GameRegistry.registerItem(Fish15, "Fish15");
      Fish16 = new ItemFish("Fish16");
      GameRegistry.registerItem(Fish16, "Fish16");
      Fish17 = new ItemFish("Fish17");
      GameRegistry.registerItem(Fish17, "Fish17");
      Fish18 = new ItemFish("Fish18");
      GameRegistry.registerItem(Fish18, "Fish18");
      Fish19 = new ItemFish("Fish19");
      GameRegistry.registerItem(Fish19, "Fish19");
      Fish20 = new ItemFish("Fish20");
      GameRegistry.registerItem(Fish20, "Fish20");
      Fish21 = new ItemFish("Fish21");
      GameRegistry.registerItem(Fish21, "Fish21");
      Fish22 = new ItemFish("Fish22");
      GameRegistry.registerItem(Fish22, "Fish22");
      Fish23 = new ItemFish("Fish23");
      GameRegistry.registerItem(Fish23, "Fish23");
      Fish24 = new ItemFish("Fish24");
      GameRegistry.registerItem(Fish24, "Fish24");
      Fish25 = new ItemFish("Fish25");
      GameRegistry.registerItem(Fish25, "Fish25");
      Fish26 = new ItemFish("Fish26");
      GameRegistry.registerItem(Fish26, "Fish26");
      Fish27 = new ItemFish("Fish27");
      GameRegistry.registerItem(Fish27, "Fish27");
      Fish28 = new ItemFish("Fish28");
      GameRegistry.registerItem(Fish28, "Fish28");
      Fish29 = new ItemFish("Fish29");
      GameRegistry.registerItem(Fish29, "Fish29");
      Fish30 = new ItemFish("Fish30");
      GameRegistry.registerItem(Fish30, "Fish30");
      Fish31 = new ItemFish("Fish31");
      GameRegistry.registerItem(Fish31, "Fish31");
      Fish32 = new ItemFish("Fish32");
      GameRegistry.registerItem(Fish32, "Fish32");
      Fish33 = new ItemFish("Fish33");
      GameRegistry.registerItem(Fish33, "Fish33");
      Fish34 = new ItemFish("Fish34");
      GameRegistry.registerItem(Fish34, "Fish34");
      Fish35 = new ItemFish("Fish35");
      GameRegistry.registerItem(Fish35, "Fish35");
      Fish36 = new ItemFish("Fish36");
      GameRegistry.registerItem(Fish36, "Fish36");
      Fish37 = new ItemFish("Fish37");
      GameRegistry.registerItem(Fish37, "Fish37");
      Fish38 = new ItemFish("Fish38");
      GameRegistry.registerItem(Fish38, "Fish38");
      Fish39 = new ItemFish("Fish39");
      GameRegistry.registerItem(Fish39, "Fish39");
      Fish40 = new ItemFish("Fish40");
      GameRegistry.registerItem(Fish40, "Fish40");
      Fish41 = new ItemFish("Fish41");
      GameRegistry.registerItem(Fish41, "Fish41");
      FishStick = new ItemFish("FishStick");
      GameRegistry.registerItem(FishStick, "FishStick");
      FishBoot = new ItemFish("FishBoot");
      GameRegistry.registerItem(FishBoot, "FishBoot");
      FishBottle = new ItemFish("FishBottle");
      GameRegistry.registerItem(FishBottle, "FishBottle");
      SeaWeed1 = (new BlockSeaPlant(Material.field_151586_h)).func_149663_c("SeaWeed1").func_149658_d("fantasyland:SeaWeed1");
      GameRegistry.registerBlock(SeaWeed1, "SeaWeed1");
      SeaWeed2 = (new BlockSeaPlant(Material.field_151586_h)).func_149663_c("SeaWeed2").func_149658_d("fantasyland:SeaWeed2");
      GameRegistry.registerBlock(SeaWeed2, "SeaWeed2");
      SeaWeed3 = (new BlockSeaPlant(Material.field_151586_h)).func_149663_c("SeaWeed3").func_149658_d("fantasyland:SeaWeed3");
      GameRegistry.registerBlock(SeaWeed3, "SeaWeed3");
      SeaWeed4 = (new BlockSeaPlant(Material.field_151586_h)).func_149663_c("SeaWeed4").func_149658_d("fantasyland:SeaWeed4");
      GameRegistry.registerBlock(SeaWeed4, "SeaWeed4");
      SeaWeed5 = (new BlockSeaPlant(Material.field_151586_h)).func_149663_c("SeaWeed5").func_149658_d("fantasyland:SeaWeed5");
      GameRegistry.registerBlock(SeaWeed5, "SeaWeed5");
   }
}
