package fantasyland.client;

import api.player.model.ModelPlayerAPI;
import api.player.model.ModelPlayerBase;
import fantasyland.monster.AssetManager;
import fantasyland.player.StoreData;
import java.util.ArrayList;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ResourceLocation;
import org.lwjgl.opengl.GL11;
import utilities.sagaobj;

public class ModePlayer extends ModelPlayerBase {
   ModelRenderer Wing01;
   ModelRenderer Wing02;
   ModelRenderer Shield;
   ModelRenderer Shape1;
   ModelRenderer armorleftarm;
   ModelRenderer armorrightleg;
   ModelRenderer armorleftleg;
   ModelRenderer armorbody;
   ModelRenderer armorrightarm;
   public float Helm_rotateAngleZ;
   public float Helm_rotateAngleY;
   public float Helm_rotateAngleX;
   public float Chest_rotateAngleZ;
   public float Chest_rotateAngleY;
   public float Chest_rotateAngleX;
   public float RightArm_rotateAngleZ;
   public float RightArm_rotateAngleY;
   public float RightArm_rotateAngleX;
   public float LeftArm_rotateAngleZ;
   public float LeftArm_rotateAngleY;
   public float LeftArm_rotateAngleX;
   public float LeftLeg_rotateAngleZ;
   public float LeftLeg_rotateAngleY;
   public float LeftLeg_rotateAngleX;
   public float RightLeg_rotateAngleZ;
   public float RightLeg_rotateAngleY;
   public float RightLeg_rotateAngleX;
   public float LeftWing_rotateAngleZ;
   public float LeftWing_rotateAngleY;
   public float LeftWing_rotateAngleX;
   public float RightWing_rotateAngleZ;
   public float RightWing_rotateAngleY;
   public float RightWing_rotateAngleX;
   public float AutoLeftWing_rotateAngleZ;
   public float AutoLeftWing_rotateAngleY;
   public float AutoLeftWing_rotateAngleX;
   public float AutoRightWing_rotateAngleZ;
   public float AutoRightWing_rotateAngleY;
   public float AutoRightWing_rotateAngleX;
   public static float modelXRotOffset = 180.0F;
   public static float modelYPosOffset = -1.5F;
   public static final ResourceLocation TEXTUREs = new ResourceLocation("fantasyland", "models/dragonset/dragonset.png");
   public static ResourceLocation TEXTUREs2 = new ResourceLocation("fantasyland", "models/dragonset/headplayer.png");
   public static ResourceLocation skintexture = new ResourceLocation("fantasyland", "models/bskin.png");
   public sagaobj modelhead = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonhelm2.saga");
   public ArrayList partmodelhead;
   public sagaobj modelhelm;
   public ArrayList partmodelhelm;
   public sagaobj modelguardhelm;
   public ArrayList partmodelguardhelm;
   public sagaobj modelflamehelm;
   public ArrayList partmodelflamehelm;
   public sagaobj modelarmor;
   public ArrayList partmodelarmor;
   public sagaobj modellarm;
   public ArrayList partmodellarm;
   public sagaobj modelrarm;
   public ArrayList partmodelrarm;
   public sagaobj modellleg;
   public ArrayList partmodellleg;
   public sagaobj modelrleg;
   public ArrayList partmodelrleg;
   public sagaobj modelguardarmor;
   public ArrayList partmodelguardarmor;
   public sagaobj modelguardLarm;
   public ArrayList partmodelguardLarm;
   public sagaobj modelguardRarm;
   public ArrayList partmodelguardRarm;
   public sagaobj modelguardLleg;
   public ArrayList partmodelguardLleg;
   public sagaobj modelguardRleg;
   public ArrayList partmodelguardRleg;
   public sagaobj modelflamearmor;
   public ArrayList partmodelflamearmor;
   public sagaobj modelflameLarm;
   public ArrayList partmodelflameLarm;
   public sagaobj modelflameRarm;
   public ArrayList partmodelflameRarm;
   public sagaobj modelflameLleg;
   public ArrayList partmodelflameLleg;
   public sagaobj modelflameRleg;
   public ArrayList partmodelflameRleg;
   public sagaobj modelflamecape;
   public ArrayList partmodelflamecape;
   public sagaobj modelhair1;
   public ArrayList parthair1;
   public sagaobj modelhair2;
   public ArrayList parthair2;
   public sagaobj modelhair3;
   public ArrayList parthair3;
   public sagaobj modelhair4;
   public ArrayList parthair4;
   public sagaobj modelhair5;
   public ArrayList parthair5;
   public sagaobj modelhair6;
   public ArrayList parthair6;
   public sagaobj modelhair7;
   public ArrayList parthair7;
   public sagaobj modelhair8;
   public ArrayList parthair8;
   public sagaobj modelhair9;
   public ArrayList parthair9;
   public sagaobj modelhair10;
   public ArrayList parthair10;
   public sagaobj modelghair1;
   public ArrayList partghair1;
   public sagaobj modelghair2;
   public ArrayList partghair2;
   public sagaobj modelghair3;
   public ArrayList partghair3;
   public sagaobj modelghair4;
   public ArrayList partghair4;
   public sagaobj modelghair5;
   public ArrayList partghair5;
   public sagaobj modelghair6;
   public ArrayList partghair6;
   public sagaobj modelghair7;
   public ArrayList partghair7;
   public sagaobj modelghair8;
   public ArrayList partghair8;
   public sagaobj modelghair9;
   public ArrayList partghair9;
   public sagaobj modelghair10;
   public ArrayList partghair10;
   public sagaobj modelghair11;
   public ArrayList partghair11;
   public sagaobj modelghair12;
   public ArrayList partghair12;
   public sagaobj modelghair13;
   public ArrayList partghair13;
   public sagaobj modelghair14;
   public ArrayList partghair14;
   public sagaobj modelghair15;
   public ArrayList partghair15;
   private ResourceLocation girltexbody;
   private ResourceLocation girltexarm;
   private ResourceLocation girltexleg;
   public sagaobj girlbody;
   public sagaobj girlrarm;
   public sagaobj girllarm;
   public sagaobj girlrleg;
   public sagaobj girllleg;
   private ResourceLocation texture;
   private ResourceLocation artex;
   public static ResourceLocation texhead = new ResourceLocation("fantasyland", "models/boy/head.png");
   public static ResourceLocation texhair = new ResourceLocation("fantasyland", "models/boy/hair.png");
   public static ResourceLocation texbody = new ResourceLocation("fantasyland", "models/boy/body.png");
   public static ResourceLocation texarm = new ResourceLocation("fantasyland", "models/boy/arm.png");
   public static ResourceLocation texleg = new ResourceLocation("fantasyland", "models/boy/leg.png");
   public sagaobj model_boy_head;
   public ArrayList part_boy_head;
   public sagaobj model_boy_hair;
   public ArrayList part_boy_hair;
   public sagaobj model_boy_rarm;
   public ArrayList part_boy_rarm;
   public sagaobj model_boy_larm;
   public ArrayList part_boy_larm;
   public sagaobj model_boy_rleg;
   public ArrayList part_boy_rleg;
   public sagaobj model_boy_lleg;
   public ArrayList part_boy_lleg;
   public sagaobj model_boy_body;
   public ArrayList part_boy_body;
   public static final ResourceLocation set01atex = new ResourceLocation("cabalaccessorys", "models/armor/set01/set1a.png");
   public static final ResourceLocation set01btex = new ResourceLocation("cabalaccessorys", "models/armor/set01/set1b.png");
   public static final ResourceLocation set01ctex = new ResourceLocation("cabalaccessorys", "models/armor/set01/set1c.png");
   public static final ResourceLocation set01dtex = new ResourceLocation("cabalaccessorys", "models/armor/set01/set1d.png");
   public static final ResourceLocation set01etex = new ResourceLocation("cabalaccessorys", "models/armor/set01/set1e.png");
   public final sagaobj set01head;
   public final ArrayList pset01head;
   public final sagaobj set01body;
   public final ArrayList pset01body;
   public final sagaobj set01rarm;
   public final ArrayList pset01rarm;
   public final sagaobj set01larm;
   public final ArrayList pset01larm;
   public final sagaobj set01rleg;
   public final ArrayList pset01rleg;
   public final sagaobj set01lleg;
   public final ArrayList pset01lleg;
   public static final ResourceLocation set06tex = new ResourceLocation("cabalaccessorys", "models/armor/set02/set06.png");
   public static final ResourceLocation set07tex = new ResourceLocation("cabalaccessorys", "models/armor/set02/set07.png");
   public static final ResourceLocation set08tex = new ResourceLocation("cabalaccessorys", "models/armor/set02/set08.png");
   public static final ResourceLocation set09tex = new ResourceLocation("cabalaccessorys", "models/armor/set02/set09.png");
   public static final ResourceLocation set10tex = new ResourceLocation("cabalaccessorys", "models/armor/set02/set10.png");
   public final sagaobj set02head;
   public final ArrayList pset02head;
   public final sagaobj set02body;
   public final ArrayList pset02body;
   public final sagaobj set02rarm;
   public final ArrayList pset02rarm;
   public final sagaobj set02larm;
   public final ArrayList pset02larm;
   public static final ResourceLocation set11tex = new ResourceLocation("cabalaccessorys", "models/armor/set03/set11.png");
   public static final ResourceLocation set12tex = new ResourceLocation("cabalaccessorys", "models/armor/set03/set12.png");
   public static final ResourceLocation set13tex = new ResourceLocation("cabalaccessorys", "models/armor/set03/set13.png");
   public static final ResourceLocation set14tex = new ResourceLocation("cabalaccessorys", "models/armor/set03/set14.png");
   public static final ResourceLocation set15tex = new ResourceLocation("cabalaccessorys", "models/armor/set03/set15.png");
   public final sagaobj set03head;
   public final ArrayList pset03head;
   public final sagaobj set03body;
   public final ArrayList pset03body;
   public final sagaobj set03cape;
   public final ArrayList pset03cape;
   public final sagaobj set03rarm;
   public final ArrayList pset03rarm;
   public final sagaobj set03larm;
   public final ArrayList pset03larm;
   public final sagaobj set03rleg;
   public final ArrayList pset03rleg;
   public final sagaobj set03lleg;
   public final ArrayList pset03lleg;
   public static final ResourceLocation set16tex = new ResourceLocation("cabalaccessorys", "models/armor/set04/set16.png");
   public static final ResourceLocation set17tex = new ResourceLocation("cabalaccessorys", "models/armor/set04/set17.png");
   public static final ResourceLocation set18tex = new ResourceLocation("cabalaccessorys", "models/armor/set04/set18.png");
   public static final ResourceLocation set19tex = new ResourceLocation("cabalaccessorys", "models/armor/set04/set19.png");
   public static final ResourceLocation set20tex = new ResourceLocation("cabalaccessorys", "models/armor/set04/set20.png");
   public final sagaobj set04head;
   public final ArrayList pset04head;
   public final sagaobj set04body;
   public final ArrayList pset04body;
   public final sagaobj set04rarm;
   public final ArrayList pset04rarm;
   public final sagaobj set04larm;
   public final ArrayList pset04larm;
   public static final ResourceLocation um1tex = new ResourceLocation("cabalaccessorys", "models/etc/umbrella1open.png");
   public final sagaobj um1md;
   public final ArrayList pum1;
   public static final ResourceLocation um2tex = new ResourceLocation("cabalaccessorys", "models/etc/umbrella2open.png");
   public final sagaobj um2md;
   public final ArrayList pum2;
   public static final ResourceLocation um3tex = new ResourceLocation("cabalaccessorys", "models/etc/umbrella3open.png");
   public final sagaobj um3md;
   public final ArrayList pum3;
   public static final ResourceLocation um4tex = new ResourceLocation("cabalaccessorys", "models/etc/umbrella4open.png");
   public final sagaobj um4md;
   public final ArrayList pum4;

   public ModePlayer(ModelPlayerAPI var1) {
      super(var1);
      this.partmodelhead = this.modelhead.groupObjects;
      this.modelhelm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonhelm.saga");
      this.partmodelhelm = this.modelhelm.groupObjects;
      this.modelguardhelm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardhelm.saga");
      this.partmodelguardhelm = this.modelguardhelm.groupObjects;
      this.modelflamehelm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameHelm.saga");
      this.partmodelflamehelm = this.modelflamehelm.groupObjects;
      this.modelarmor = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonchest.saga");
      this.partmodelarmor = this.modelarmor.groupObjects;
      this.modellarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonLarm.saga");
      this.partmodellarm = this.modellarm.groupObjects;
      this.modelrarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonRarm.saga");
      this.partmodelrarm = this.modelrarm.groupObjects;
      this.modellleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonLleg.saga");
      this.partmodellleg = this.modellleg.groupObjects;
      this.modelrleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/dragonRleg.saga");
      this.partmodelrleg = this.modelrleg.groupObjects;
      this.modelguardarmor = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardchest.saga");
      this.partmodelguardarmor = this.modelguardarmor.groupObjects;
      this.modelguardLarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardLarm.saga");
      this.partmodelguardLarm = this.modelguardLarm.groupObjects;
      this.modelguardRarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardRarm.saga");
      this.partmodelguardRarm = this.modelguardRarm.groupObjects;
      this.modelguardLleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardLleg.saga");
      this.partmodelguardLleg = this.modelguardLleg.groupObjects;
      this.modelguardRleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/guardRleg.saga");
      this.partmodelguardRleg = this.modelguardRleg.groupObjects;
      this.modelflamearmor = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameChest.saga");
      this.partmodelflamearmor = this.modelflamearmor.groupObjects;
      this.modelflameLarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameLarm.saga");
      this.partmodelflameLarm = this.modelflameLarm.groupObjects;
      this.modelflameRarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameRarm.saga");
      this.partmodelflameRarm = this.modelflameRarm.groupObjects;
      this.modelflameLleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameLleg.saga");
      this.partmodelflameLleg = this.modelflameLleg.groupObjects;
      this.modelflameRleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameRleg.saga");
      this.partmodelflameRleg = this.modelflameRleg.groupObjects;
      this.modelflamecape = (sagaobj)AssetManager.getObjModel("fantasyland:models/dragonset/flameCape.saga");
      this.partmodelflamecape = this.modelflamecape.groupObjects;
      this.modelhair1 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair1.saga");
      this.parthair1 = this.modelhair1.groupObjects;
      this.modelhair2 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair2.saga");
      this.parthair2 = this.modelhair2.groupObjects;
      this.modelhair3 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair3.saga");
      this.parthair3 = this.modelhair3.groupObjects;
      this.modelhair4 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair4.saga");
      this.parthair4 = this.modelhair4.groupObjects;
      this.modelhair5 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair5.saga");
      this.parthair5 = this.modelhair5.groupObjects;
      this.modelhair6 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair6.saga");
      this.parthair6 = this.modelhair6.groupObjects;
      this.modelhair7 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair7.saga");
      this.parthair7 = this.modelhair7.groupObjects;
      this.modelhair8 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair8.saga");
      this.parthair8 = this.modelhair8.groupObjects;
      this.modelhair9 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair9.saga");
      this.parthair9 = this.modelhair9.groupObjects;
      this.modelhair10 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/hair10.saga");
      this.parthair10 = this.modelhair10.groupObjects;
      this.modelghair1 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair1.saga");
      this.partghair1 = this.modelghair1.groupObjects;
      this.modelghair2 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair2.saga");
      this.partghair2 = this.modelghair2.groupObjects;
      this.modelghair3 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair3.saga");
      this.partghair3 = this.modelghair3.groupObjects;
      this.modelghair4 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair4.saga");
      this.partghair4 = this.modelghair4.groupObjects;
      this.modelghair5 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair5.saga");
      this.partghair5 = this.modelghair5.groupObjects;
      this.modelghair6 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair6.saga");
      this.partghair6 = this.modelghair6.groupObjects;
      this.modelghair7 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair7.saga");
      this.partghair7 = this.modelghair7.groupObjects;
      this.modelghair8 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair8.saga");
      this.partghair8 = this.modelghair8.groupObjects;
      this.modelghair9 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair9.saga");
      this.partghair9 = this.modelghair9.groupObjects;
      this.modelghair10 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair10.saga");
      this.partghair10 = this.modelghair10.groupObjects;
      this.modelghair11 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair11.saga");
      this.partghair11 = this.modelghair11.groupObjects;
      this.modelghair12 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair12.saga");
      this.partghair12 = this.modelghair12.groupObjects;
      this.modelghair13 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair13.saga");
      this.partghair13 = this.modelghair13.groupObjects;
      this.modelghair14 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair14.saga");
      this.partghair14 = this.modelghair14.groupObjects;
      this.modelghair15 = (sagaobj)AssetManager.getObjModel("fantasyland:models/hair/ghair15.saga");
      this.partghair15 = this.modelghair15.groupObjects;
      this.girltexbody = new ResourceLocation("fantasyland:models/girl/body.png");
      this.girltexarm = new ResourceLocation("fantasyland:models/girl/arm.png");
      this.girltexleg = new ResourceLocation("fantasyland:models/girl/leg.png");
      this.girlbody = (sagaobj)AssetManager.getObjModel("fantasyland:models/girl/body.saga");
      this.girlrarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/girl/rarm.saga");
      this.girllarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/girl/larm.saga");
      this.girlrleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/girl/rleg.saga");
      this.girllleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/girl/lleg.saga");
      this.artex = new ResourceLocation("fantasyland:textures/indyarmor/ar01_1.png");
      this.model_boy_head = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/head.saga");
      this.part_boy_head = this.model_boy_head.groupObjects;
      this.model_boy_hair = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/hair.saga");
      this.part_boy_hair = this.model_boy_hair.groupObjects;
      this.model_boy_rarm = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/rarm.saga");
      this.part_boy_rarm = this.model_boy_rarm.groupObjects;
      this.model_boy_larm = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/larm.saga");
      this.part_boy_larm = this.model_boy_larm.groupObjects;
      this.model_boy_rleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/rleg.saga");
      this.part_boy_rleg = this.model_boy_rleg.groupObjects;
      this.model_boy_lleg = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/lleg.saga");
      this.part_boy_lleg = this.model_boy_lleg.groupObjects;
      this.model_boy_body = (sagaobj)AssetManager.getObjModel("fantasyland:models/boy/body.saga");
      this.part_boy_body = this.model_boy_body.groupObjects;
      this.set01head = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/head.saga");
      this.pset01head = this.set01head.groupObjects;
      this.set01body = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/body.saga");
      this.pset01body = this.set01body.groupObjects;
      this.set01rarm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/rarm.saga");
      this.pset01rarm = this.set01rarm.groupObjects;
      this.set01larm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/larm.saga");
      this.pset01larm = this.set01larm.groupObjects;
      this.set01rleg = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/rleg.saga");
      this.pset01rleg = this.set01rleg.groupObjects;
      this.set01lleg = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set01/lleg.saga");
      this.pset01lleg = this.set01lleg.groupObjects;
      this.set02head = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set02/head.saga");
      this.pset02head = this.set02head.groupObjects;
      this.set02body = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set02/body.saga");
      this.pset02body = this.set02body.groupObjects;
      this.set02rarm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set02/rarm.saga");
      this.pset02rarm = this.set02rarm.groupObjects;
      this.set02larm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set02/larm.saga");
      this.pset02larm = this.set02larm.groupObjects;
      this.set03head = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/head.saga");
      this.pset03head = this.set03head.groupObjects;
      this.set03body = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/body.saga");
      this.pset03body = this.set03body.groupObjects;
      this.set03cape = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/cape.saga");
      this.pset03cape = this.set03cape.groupObjects;
      this.set03rarm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/rarm.saga");
      this.pset03rarm = this.set03rarm.groupObjects;
      this.set03larm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/larm.saga");
      this.pset03larm = this.set03larm.groupObjects;
      this.set03rleg = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/rleg.saga");
      this.pset03rleg = this.set03rleg.groupObjects;
      this.set03lleg = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set03/lleg.saga");
      this.pset03lleg = this.set03lleg.groupObjects;
      this.set04head = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set04/head.saga");
      this.pset04head = this.set04head.groupObjects;
      this.set04body = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set04/body.saga");
      this.pset04body = this.set04body.groupObjects;
      this.set04rarm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set04/rarm.saga");
      this.pset04rarm = this.set04rarm.groupObjects;
      this.set04larm = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/armor/set04/larm.saga");
      this.pset04larm = this.set04larm.groupObjects;
      this.um1md = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/etc/umbrella1open.saga");
      this.pum1 = this.um1md.groupObjects;
      this.um2md = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/etc/umbrella2open.saga");
      this.pum2 = this.um2md.groupObjects;
      this.um3md = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/etc/umbrella3open.saga");
      this.pum3 = this.um3md.groupObjects;
      this.um4md = (sagaobj)AssetManager.getObjModel("cabalaccessorys:models/etc/umbrella4open.saga");
      this.pum4 = this.um4md.groupObjects;
      this.armorleftarm = new ModelRenderer(this.modelPlayer, 40, 16);
      this.armorleftarm.field_78809_i = true;
      this.armorleftarm.func_78789_a(-1.0F, -2.0F, -2.0F, 4, 12, 4);
      this.armorleftarm.func_78793_a(5.0F, 2.0F, 0.0F);
      this.armorleftarm.func_78787_b(64, 32);
      this.armorrightleg = new ModelRenderer(this.modelPlayer, 0, 16);
      this.armorrightleg.func_78789_a(-2.0F, 0.0F, -2.0F, 4, 12, 4);
      this.armorrightleg.func_78793_a(-2.0F, 12.0F, 0.0F);
      this.armorrightleg.func_78787_b(64, 32);
      this.armorrightleg.field_78809_i = true;
      this.armorleftleg = new ModelRenderer(this.modelPlayer, 0, 16);
      this.armorleftleg.field_78809_i = true;
      this.armorleftleg.func_78789_a(-2.0F, 0.0F, -2.0F, 4, 12, 4);
      this.armorleftleg.func_78793_a(2.0F, 12.0F, 0.0F);
      this.armorleftleg.func_78787_b(64, 32);
      this.armorbody = new ModelRenderer(this.modelPlayer, 16, 16);
      this.armorbody.func_78789_a(-4.0F, 0.0F, -2.0F, 8, 12, 4);
      this.armorbody.func_78793_a(0.0F, 0.0F, 0.0F);
      this.armorbody.func_78787_b(64, 32);
      this.armorbody.field_78809_i = true;
      this.armorrightarm = new ModelRenderer(this.modelPlayer, 40, 16);
      this.armorrightarm.func_78789_a(-3.0F, -2.0F, -2.0F, 4, 12, 4);
      this.armorrightarm.func_78793_a(-5.0F, 2.0F, 0.0F);
      this.armorrightarm.func_78787_b(64, 32);
      this.armorrightarm.field_78809_i = true;
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      EntityPlayer player = (EntityPlayer)entity;
      StoreData px = StoreData.get(player);
      if (px.Sex == 0) {
         if (px.Hair == 0) {
            TEXTUREs2 = new ResourceLocation("fantasyland", "models/dragonset/headplayer_" + player.func_70096_w().func_75679_c(30) + ".png");
            skintexture = new ResourceLocation("fantasyland", "models/bskin.png");
         } else {
            TEXTUREs2 = new ResourceLocation("fantasyland", "models/dragonset/headplayer2_" + player.func_70096_w().func_75679_c(30) + ".png");
            skintexture = new ResourceLocation("fantasyland", "models/bskin.png");
         }
      } else if (px.Hair == 0) {
         TEXTUREs2 = new ResourceLocation("fantasyland", "models/dragonset/headplayerg_" + player.func_70096_w().func_75679_c(30) + ".png");
         skintexture = new ResourceLocation("fantasyland", "models/gskin.png");
      } else {
         TEXTUREs2 = new ResourceLocation("fantasyland", "models/dragonset/headplayerg2_" + player.func_70096_w().func_75679_c(30) + ".png");
         skintexture = new ResourceLocation("fantasyland", "models/gskin.png");
      }

      GL11.glPushMatrix();
      Minecraft.func_71410_x().field_71446_o.func_110577_a(skintexture);
      GL11.glDisable(2896);
      this.modelPlayer.field_78115_e.func_78785_a(f5);
      this.modelPlayer.field_78113_g.func_78785_a(f5);
      this.modelPlayer.field_78112_f.func_78785_a(f5);
      this.modelPlayer.field_78123_h.func_78785_a(f5);
      this.modelPlayer.field_78124_i.func_78785_a(f5);
      GL11.glPopMatrix();
   }

   public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
   }

   public void rotate(float rotX, float rotY, float rotZ) {
      GL11.glRotatef(rotX, 1.0F, 0.0F, 0.0F);
      GL11.glRotatef(rotY, 0.0F, 1.0F, 0.0F);
      GL11.glRotatef(rotZ, 0.0F, 0.0F, 1.0F);
   }

   public void rotate(float rotation, float angleX, float angleY, float angleZ) {
      GL11.glRotatef(rotation, angleX, angleY, angleZ);
   }

   public void translate(float posX, float posY, float posZ) {
      GL11.glTranslatef(posX, posY, posZ);
   }

   public void scale(float scaleX, float scaleY, float scaleZ) {
      GL11.glScalef(scaleX, scaleY, scaleZ);
   }

   public void rotationpart(ModelRenderer part) {
      GL11.glTranslatef(part.field_78800_c * 0.0625F, part.field_78797_d * 0.0625F, part.field_78798_e * 0.0625F);
      if (part.field_78808_h != 0.0F) {
         GL11.glRotatef(part.field_78808_h * 57.295776F, 0.0F, 0.0F, 1.0F);
      }

      if (part.field_78796_g != 0.0F) {
         GL11.glRotatef(part.field_78796_g * 57.295776F, 0.0F, 1.0F, 0.0F);
      }

      if (part.field_78795_f != 0.0F) {
         GL11.glRotatef(part.field_78795_f * 57.295776F, 1.0F, 0.0F, 0.0F);
      }

   }
}
